name: Build and Push Docker Image

on:
  push:
    branches:
<<<<<<< HEAD
      - main
=======
      - main   # Runs workflow when code is pushed to main branch
>>>>>>> 4f2a754 (Initial commit with creation of app.py and docker-compose and docker-build)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
<<<<<<< HEAD
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.huzaifa5 }}/url-shortener:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.huzaifa5 }}/url-shortener:latest
=======
      # Step 1: Checkout repo
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Login to DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.huzaifa5 }}
          password: ${{ secrets.dckr_pat_kZxXoRyrPBq7R2m4EF5DX-Muphc }}

      # Step 3: Build Docker image
      - name: Build Docker Image
        run: docker build -t huzaifa5/notes-app:latest .

      # Step 4: Push Docker image to DockerHub
      - name: Push Docker Image
        run: docker push huzaifa5/notes-app:latest
>>>>>>> 4f2a754 (Initial commit with creation of app.py and docker-compose and docker-build)
