name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.huzaifa5 }}
          password: ${{ secrets.dckr_pat_pIFjRbzp5zJTFSEhVjr5y55NpKo }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.huzaifa5 }}/url-shortener:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.huzaifa5 }}/url-shortener:latest
